sudo: required
env:
  global:
  - DIST_REPO="f5-sphinx-theme"
  - USER_REPO=$(echo $TRAVIS_REPO_SLUG | cut -f -1 -d / )
  - BUILD_HTML_DIR=$TRAVIS_BUILD_DIR/test-deploy/docs/_build/html
  - AWS_STAGING="https://d3s2z99mfhr69y.cloudfront.net"
  - secure: "V+e0n4WU7UYZuNzdv9qajv1KU+Okw9mhwK0XlEvow0WQ3vIVzHUXDd7peMoVk0xSO5uFbfmdQbAFymKUZONyJkGiWvJXybLjiQMhU484e24WsYL2rHzV8OAjuYf29NHd7Pmm41mqou1jTfuJkU7bGdLNFKNil3QFFxwDN/7EOZJ8r2EdLOEqvo4dDhkTRbQk4aBXcpK5l3XFW8rWA7FS/bITzG2iEWan/qAFVTsWRG5dlHegusP/pf7EQX2LaZ/97bqLjdS8KmGORE7IU0AkO1vRapj5D6nJF7fKuO3AwzVsDqT9oEqE+K+qSgvLE7KdY1U4ZNo+S4jz+DXEfJ4b6yxOQ+kFCxexDvjnZf4FP2vN/Jt5kZtSzKlB2MIJUpH7GMpffvS24ei9NKHmxF68Mgyerkwj8XmzM5rTPeBNXwvzJsxyP0wy858jSYCmshrby1WuRfEhoXz6ClbOSd1WjRSp4KuNnQ34tp8w1wuNGiCc7PJ/pJaVDlEJxJeE3g7Tk8eRJJoVFpHFINd6sP+SLLz5gQFOGK3pVgxmFQOgJKlTLxVTU4xLDoAW433tpZ182+BdZIopCjHcMTAmcBYbpW9Y4QBHXSb1snwJpC2yVztW975XDT5wd8QPo9WQRjuU2nNvGJ3stM0hy6uIfzLEsY744K2MiLy+MwkhirUrgqY="
  - secure: "cbMkZzTwrXYcDwObRp/zEjbG2Z/nIkoTarqfy6HnVNjXNj3cuIBhHD7S3nNgyBohjJrACssBnVvbzqgkuzANJaHfldPIk2ZPRqjT2xAIxpHVu3LWDMgPXf2qguP5VDWQ7y3hnuyWBMv8iSZBoUwjcmG0L5ePyYNrV9U0t+HKBnu4eCjHAjs1DztItaLhuIi4iNr40GQM0RdYsMe5/f+/sKNz5GCyzI4PdGXyNdgLIYbda7CDGESnYge0nzD7pMCC+FVT6B7Ds6Q5twGJ7mvcEYBUqW1YdS/Zyp/6I8DbwvGtBF7Y4pp6c382EMSS9pMe5LuHHMhQQy0FDThb8ZuO2SPdAFyvWajmNRIVkAHiB5z2zKpAUPjw5KCAakN6nxwt+vuzn/IeI/sT4Bpycq4MYHpOukACYmJmuGKCf1M8IgMX35KeeEkRRUKdtW18aGddpuhEliCMa1QeuC6bpNY2AlI212d6r8UrexBhPIbFkmf7Pps82F9aVwJrv0Mek5m/bHOPlwf7401CZCv2OY7r8xlm6hntgyUj4HLJWYDyfdW4tacJlM2RKlp8AC3pzVXx+zt431KfdhBqkfT4NDYEL7k2UzIxjMYh1lgs4wHvNJLOFIZ7rYKM0V7cR+TGTPERbtGCIbsdoorzn79MTOUrQy/EGvVJBXA33C5iow5ddhI="
  # CDN distrubution id
  - secure: "XXppjwpoQyVJ1iVYzDPZY/kNk1O0Prb6aQw58E03LOeS1AZl7YKuHw2ljlDo5pGtM2/9XsD/0Vbppva7claTXn1vaFD2JERPc2RwwWkbehmBqQIdEkMoUld1SB5j7k0lkHV4QmwcXBo+b+UOtilWdweRFgFBoS6rC7EOw5hKvAO2zFy50BbM8IH9ZH+aQyhEMQrZV0DqNSpY0JpG0ZL4RSMgniDs27TZN8WNDSS9xbYl/0sMvuYXhUV0JdsrHFeyjrNln2rGmvI9LvfkQkOU3gypHQxKVob1qtr2qVyoq65XtuNbqGVBevwbJQt2/rFFlRTw6y3LFNgoWwvBaAXgEZG3s4go3Z/D4q6LRuSACetC/SjK3VJGg0AtIQ9s2vOb8hQnDx2FO5BL3eTJ44AWHxzjyVxj9gw87xG1yGBRG8Wkf+MfHKMh6QjHt3F1t2S7hM3ErOG25Qby1zFkV4damqCmGkqHPycoZqqlp1731m7cJzgH02D5yUyR0BfiMM+Bb/IqVpX7n/8dXqQxNC7AvI5nTwFyVjD2LuVn1UY5njT5I0CT7qpRWRE1YQfgwAr9m5hl7chDI3YcdPE5DqlRQn/iocQryn0VUq4vZJ4rA3fxXcxtqBpblnqNS1J/8b1fEnOsNPpR+7c9LPYeOrpJWzbUVHlyOgyTwMkmuK2u984="

services:
- docker
language: python
python:
- '2.7'
before_install:
- git config --global user.email "OpenStack_TravisCI@f5.com"
- git config --global user.name "f5-travisci"
install:
- gem install html-proofer
- pip install awscli
- pip install ./
script:
- htmlproofer --check_html --checks-to-ignore "LinkCheck,ImageCheck,ScriptCheck" --report_invalid_tags
  --report-script-embeds f5_sphinx_theme/
- test/theme-test.sh
- cp -R $BUILD_HTML_DIR ${DIST_REPO}/travis-builds/${USER_REPO}/${TRAVIS_BUILD_NUMBER}
addons:
  artifacts: true
  env:
  - ARTIFACTS_KEY=$ACCESS_KEY_ID
  - ARTIFACTS_SECRET=$AWS_SECRET_ACCESS_KEY
  - ARTIFACTS_BUCKET=clouddocs.f5networks.net
  paths:
  - ${DIST_REPO}/travis-builds/${USER_REPO}/${TRAVIS_BUILD_NUMBER}

deploy:
- provider: pypi
  user: "$PYPI_USER"
  password: "$PYPI_PASSWORD"
  server: https://pypi.python.org.pypi
  on:
    tags: true
  skip_cleanup: true
#- provider: s3
#  skip_cleanup: true
#  on:
#    repo: $TRAVIS_REPO_SLUG
#    all_branches: true
#  access_key_id: $ACCESS_KEY_ID
#  secret_access_key: $AWS_SECRET_ACCESS_KEY
#  bucket: clouddocs.f5networks.net
#  acl: authenticated_read
#  local_dir: $BUILD_HTML_DIR
#  upload_dir: $DIST_REPO/travis-builds/$USER_REPO/$TRAVIS_BUILD_NUMBER

after_deploy:
  - echo "Docs published to:"
  - echo "${AWS_STAGING}/${DIST_REPO}/travis-builds/${USER_REPO}/${TRAVIS_BUILD_NUMBER}"
  # create CloudFront invalidation to clear old objects from cache
  #- aws cloudfront create-invalidation --distribution-id $CDN_DIST_ID --paths "$DIST_REPO/travis-builds/$USER_REPO/$TRAVIS_BUILD_NUMBER/*"



