sudo: required
env:
  global:
  - DIST_REPO="f5-sphinx-theme"
  - USER_REPO=$(echo $TRAVIS_REPO_SLUG | cut -f -1 -d / )
  - BUILD_HTML_DIR=$TRAVIS_BUILD_DIR/test-deploy/docs/_build/html
  - $AWS_STAGING="https://d3s2z99mfhr69y.cloudfront.net"
services:
- docker
language: python
python:
- '2.7'
before_install:
- git config --global user.email "OpenStack_TravisCI@f5.com"
- git config --global user.name "f5-travisci"
install:
- gem install html-proofer
- pip install ./
script:
- htmlproofer --check_html --checks-to-ignore "LinkCheck,ImageCheck,ScriptCheck" --report_invalid_tags
  --report-script-embeds f5_sphinx_theme/
- test/theme-test.sh
deploy:
- provider: s3
  skip_cleanup: true
  on:
    repo: $TRAVIS_REPO_SLUG
    all_branches: true
  access_key_id:
    secure: "p0fNNAWq0sYMqH0LS4c90n5mZ/sEwJAgHD433Uv8OYJSGoKquzHDLYHqce3QWANW2s7M9hIOyj08yk2TAjDHMwNpY/gQkWTDbzro07cmfBFGZTDWyM/+t+UsY01/kaThd3TZp+R5UTSHu+epNSrLGhrB7wkMzgoT3LWM6jS8BPN1pty71ASzfqKgmZA6qXahgxNMIyFBlneaC5XpTmb96RrshgqVGgEqbr+gk5I6D5u5XxTFDm2gIIZZ5BqzomuLVKqaHAD0fM2J32vEeur6bCNLvR0Mfs0teIV3YoNXyHS6QpUTE8SXpV3eHWEHNrGgZM+x1p6zpkabkFSIqdU0S9SykqT81noXGRMx6p8SzJLEYjahiQjPsslEVCVKCKHMhv1EGUjilwXbmKbI8ehrCRoa+sUOgyKg0L0j6KqBssdeQr2/XcG36oGSW/1vW06f8UbTTLsEn/WxMLzXNVNEyObBVIcI5IDCfl6S1DoR5ki9YNEfqAAsx2UYSmlRR0gW3UrNTOS6BTeAAnUUFvXz6tStvfHRIG38B8hAzvWoc+wQPQOjJRbA+aofcJKurWdSzDU4jYsyAbuVWH+AXx6vz6RtalLlCmZA+yIYg6YbqVkuT97+XxB35MvO+AY7jZcQ95X+naYTrhmKZMF28b/708UidqC0+Ajc9Dzv6s/ZbJ8="
  secret_access_key:
    secure: "gSeAaw8SK0a0kOK9ZYUwIYGE2H2e5Qm/HIl1lJP75W6F+Wu37Y7QKscvQFJ/9Sge3bo3ZCvBjhttlhBH1LGaIRxo8B0aF/AUw9dL8KJqLAWw7e6kp/rBE3UTvPz7bHTT8jXQvkLpeN3mtQxFb3lMIc/o6zf46jA8MGXowLBsM7G8OogJExF2hZxBOkED+PHsIQnN/9wwAbE4aQvJZG3VtlnZhLC4NCRaV5nqtsYrayeYsrVW3dkrRYghyxP7RrX7qHqCqNW3j8vPP4Zh1ljc0EkP4DxX2tLgiDAI/SPx+4p83yc7KkNwNX2PVRpX6MalDflFl9Hw4z1sekVREdynWIhodMfJblcfMWn26+VyN62D+YDTGb7yksJWAJGduP4UBnCvviwbHpOs4AN7PqG1i2BDJtcJiFPuRJ4KN4eHZ01DnIj7sYnyRaZiFhyeeGENX39q0D3BWXYxn+IRmsVHeJ+ey5e3P286w7lxsK/1BHd/1aPh0TiWaEblUl4VSHSMteDWCm5B7bXNq9W3YMnH1daEP5r7Cnj3jusg0B7lbA9u5BXlNiLEyTjfftxkbKqyK22btE2j/Rv2efaUxdzFxtyRLmNrAUq9wMzvvZbKFTdR5GSE/OzgFiAIVkG3cydqD2+4jOoUhZ4BWS1Skq3bpwx4+9wujqG5DLmfZ/sYLgE="
  bucket: clouddocs.f5networks.net
  acl: authenticated_read
  local_dir: $BUILD_HTML_DIR
  upload_dir: $DIST_REPO/travis-builds/$USER_REPO/$TRAVIS_BUILD_NUMBER
- provider: pypi
  user: "$PYPI_USER"
  password: "$PYPI_PASSWORD"
  server: https://pypi.python.org.pypi
  on:
    tags: true
  skip_cleanup: true

after_deploy:
  - echo "Docs published to:"
  - echo "${AWS_STAGING}/${DIST_REPO}/travis-builds/${USER_REPO}/${TRAVIS_BUILD_NUMBER}"



