sudo: required
env:
  global:
  - DIST_REPO="f5-sphinx-theme"
  - USER_REPO=$(echo $TRAVIS_REPO_SLUG | cut -f -1 -d / )
  - BUILD_HTML_DIR=$TRAVIS_BUILD_DIR/test-deploy/docs/_build/html
  - AWS_STAGING="https://d3s2z99mfhr69y.cloudfront.net"
  - secure: "Vyh0SR4qvLanamOltoLZyD33mTWJPwunsy0/DEJRGKvYHvBOglJiwzuWubVmvDxL63zT3f6xobbvrp4BNI15H+hKSxgeDM73zqPcIlsCmCoIYjPk/wuqZCYg/TYMjPeyCgxrtdIvxi2ATNjjFuJMPgpHaxLfK4IesyLs1lvCkSpcUaG+2l9EEBT93V2Pmhn6Z4XUNcaYkLDP/EKsj+BVPHAbOe3Ra0QIAYi4H/cdFUjDK4q7iOCT+9ImuFZBlELsh9mn14BXMJ53uyh/W7O8T8TEsxFM30YIac9906Hnro/idSFpWys14XU9ZLIbjfj331RzYOI+oqiysDcN8y/mXQCibNUcnlV4CUd4J/kyr5cj5xSgQQfuAozs3rSgmXIqDXODAfPNFCrdaTh45Stm3QMgfKGwxlW0YOIfBD6FQn/NatDRShLGNPNMP98pP8jjT6q/cP07STtZZHwA535M0WEeVVFsP4vaxz9A4o8CdDU9l3OuYIQ8wyiWS2pWfAEXUiGBRBgr32p1lMTjnXZvAXwKSqi/qOcF3rpCMBt8O5KrHHRYZ+J2ZO2fRJudSRdUyTCnnCm0hHP8SlfRyHj1hg0wVxI1yiVgi4g+3mV9MmT3E84d0FMP2sgNnZzsmqv4cE5ifeXVBpVbofhBmmro55NhSDctQVjeT8I1HQUxbdI="
  - secure: "fSUMFSeHoayO3+wwb41BxpyErBzM1WwzgrXiWbMiUvmFll5Nows1Wm9QmTNcSg7+n99qCIA1EjfZH5VJd5T+kNKYSXj9d8yr5BZlrIK20g5mSq+0b+p6oClxe/84OEr8GC6vDf1lhfTLSn8ZNHjzhd7l+JFNDoTtKWNn5fU2d2ygGcgcNleVawHykoNwyGQqD8ELpt0Se8VSYuELA/+y1qQmQI6ITai8BYuaTYa0DQ2yPZvfk4YVtKh1MYzXXf0Sy4bLdmf1erqhkfryaj0Sg4xOkZn5RZdoJxjnNeQPwLFSpCWt5QJ6PcEOucoxswuIOlaL7H7zRRf6OtEvSCsOoD1qViA/wwrphB+CILphzzFXEn0LcIJdlKUtAUsQk7UysNH3R9QXtoHi/1JaPlQ2nSztzzOLnR6iou4tUYluYXpROm6Vum1KMdBzKb3LZnHdolPnGSAuPRSizPwUYp76XV+Gc60/TSZuYM5EmNr2EzO6lQolnvYydLL68eJ08bHztv/BzGSP3ddrwTh7Z+PTf5G+jtdYdgYrv3uX2YzShkXsVH3DCcHRIM0Okc1DjnEAKhbR+ax8YN/z/5cbEUKEdk/1ffRIUXn2EMlPEiR1wXvswS4Oyf/EDjmWJAzbSDBQwWYTqy8jOvnnFRPQwLhWUHRp/gOOH1aO81AnVRBWHYU="
  # CDN distrubution id
  - secure: "HsgIH6E9VpxDXSkST+hsGp+CYhX63r4iWFAZJ70+w8UDHTha4xGJamrICOqoSGzqS/RxScH57eHi6TLPp9sq9mwobXervzPH8Wc29D/SJQy/i0CfA1ogT3NfMNpYtrqxBWnM52Iw+yxsDwaVZGJI/HAorK6aC2fzAc2SBMQym9GdyA4lfzT/6rRU1kGkYzzKnzQ9Mwc7yhAOPK80sbAmDUO4t4Ze8So8JBBdh1Kh1jg403YhyrQGb1Ow3LurPFO+YCR51uUtPXsNnBl3tyDZyFGhhhV+QYvOVrIaCIMGQDwdlj4ykWMC5FrOdBfjszn8RWwP/QHjOiWmbQEdPwjuQq6NgQNIQOuUFniIrqF8H4sPygvAOeY7EUHjf/0QXy0JSUWOaYfJNq6hhCUMdzK71cYNYDCqAqb6JJkN91toKGidrYuXvLZQnsBsFvXTTAZlR3rsUt0px4ZrOZIBLTJ62zgaR207DlvRfGPnEGBVOGPsFgp9bIXoXgg8nZeolOy3qxXLTSnkxsAIuVRAPwP7GuAy9Sb7jKWDrYpUxC0JPX9B0xzAFSpc7mukjwJg0Te4cD67SVAcSLTTmtSTW4VDskJd1VlvEL6eltUpLFzY44WlEoxgI0Ad/9DcxzZ5IcYkJW6tnyJYGHYw6qvxOe0dngoY9wMXMo3Cnpk8WKWZjx4="
  - ARTIFACTS_KEY=$AWS_ACCESS_KEY_ID
  - ARTIFACTS_SECRET=$AWS_SECRET_ACCESS_KEY
  - ARTIFACTS_BUCKET=clouddocs.f5networks.net

services:
- docker
language: python
python:
- '2.7'
before_install:
- git config --global user.email "OpenStack_TravisCI@f5.com"
- git config --global user.name "f5-travisci"
install:
- gem install html-proofer
- pip install awscli
- pip install ./
script:
- htmlproofer --check_html --checks-to-ignore "LinkCheck,ImageCheck,ScriptCheck" --report_invalid_tags
  --report-script-embeds f5_sphinx_theme/
- test/theme-test.sh
- mkdir ${DIST_REPO}/travis-builds/${USER_REPO}/${TRAVIS_BUILD_NUMBER}
- cp -R $BUILD_HTML_DIR ${DIST_REPO}/travis-builds/${USER_REPO}/${TRAVIS_BUILD_NUMBER}
addons:
  artifacts: true
  paths:
  - ${DIST_REPO}/travis-builds/${USER_REPO}/${TRAVIS_BUILD_NUMBER}

deploy:
- provider: pypi
  user: "$PYPI_USER"
  password: "$PYPI_PASSWORD"
  server: https://pypi.python.org.pypi
  on:
    tags: true
  skip_cleanup: true
#- provider: s3
#  skip_cleanup: true
#  on:
#    repo: $TRAVIS_REPO_SLUG
#    all_branches: true
#  access_key_id: $ACCESS_KEY_ID
#  secret_access_key: $AWS_SECRET_ACCESS_KEY
#  bucket: clouddocs.f5networks.net
#  acl: authenticated_read
#  local_dir: $BUILD_HTML_DIR
#  upload_dir: $DIST_REPO/travis-builds/$USER_REPO/$TRAVIS_BUILD_NUMBER

after_deploy:
  - echo "Docs published to:"
  - echo "${AWS_STAGING}/${DIST_REPO}/travis-builds/${USER_REPO}/${TRAVIS_BUILD_NUMBER}"
  # create CloudFront invalidation to clear old objects from cache
  #- aws cloudfront create-invalidation --distribution-id $CDN_DIST_ID --paths "$DIST_REPO/travis-builds/$USER_REPO/$TRAVIS_BUILD_NUMBER/*"



